#server:
#  port: 9001
#  servlet:
#    context-path: /hello
#spring:
#  mvc:
#    servlet:
#      path: /world

  application:
    name: cloud-feign-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.100:8848 #配置Nacos地址